#!/bin/bash
# shellcheck disable=SC2063,SC2129,SC2181,SC2162
# Usage:
# git hotfix create|c [name]
# git hotfix finish|f [name]
# Colors
red="\033[31m"
green="\033[32m"
yellow="\033[33m"
normal="\033[0m"

# Set default subcommand
CMD=${1:-create}

# make sure the aliases trigger the right
# subcommand
case "$CMD" in
c | create)
    CMD='create'
    ;;
p | publish)
    CMD='publish'
    ;;
f | finish)
    CMD='finish'
    ;;
esac

# get the settings from git config
BRANCHPREFIX=$(git config --get nextflow.prefix.hotfix)
BRANCHFROM=$(git config --get nextflow.branch.next)
BRANCHRELEASE=$(git config --get nextflow.branch.main)
STRATEGY=$(git config --get nextflow.general.strategy)
HOTFIXNAME=$2
BRANCH="${BRANCHPREFIX}$HOTFIXNAME"

# make sure the 'next' branch exists
# use the 'main' branch as a fallback
if ! git rev-parse --quiet --verify "$BRANCHFROM" &>/dev/null; then
    BRANCHFROM=$BRANCHRELEASE
fi

# tests for a clean state
WORKINGDIRDIRTY=$(git status --porcelain)
BRANCHEXISTS=$(git rev-parse --quiet --verify "$BRANCH")
CURRENTBRANCH=$(git branch | grep \* | cut -d ' ' -f2)

# Help function showing usage of the command
usage() {
    echo -e "Usage:\ngit hotfix create|c [name]"
    echo -e "git hotfix publish|p [name]"
    echo -e "git hotfix finish|f [name]\n"
}

# merges hotfix branch into develop.
function finishHotfix {

    # assume current branch is a hotfix/ branch
    #  if no hotfix name is given
    if [ -z "$HOTFIXNAME" ]; then

        # use current branch as the target
        BRANCH=$CURRENTBRANCH

        # extract hotfix name from hotfix/[name] branch
        HOTFIXNAME=${BRANCH/"$BRANCHPREFIX"/''}

        # Make sure the branch starts with the hotfix/ prefix
        # otherwise abort and force manual usage over [name] parameter.
        if [[ ! "$BRANCH" =~ $BRANCHPREFIX ]]; then
            echo -e "\nERR: Couldn't find the right hotfix branch.\n"
            echo -e "Please give either a name like this:"
            echo -e "=> git hotfix finish menu-fixes@v1.10.0"
            echo -e "or checkout the branch you want to finish.\n"
            usage
            exit 1
        fi
    fi

    echo ""

    # The setting "nextflow.general.strategy" controls how
    # additional branches are merged into the 'next' and 'main' branch.
    case $STRATEGY in
    alternate)
        # merge without fast-forward into 'next' branch
        git checkout "$BRANCHFROM"
        git merge --squash "$BRANCH"
        git commit -m "[fix] Implement $BRANCH"
        # tag the merge with hotfix name
        git tag "$BRANCH"
        # and delete its hotfix/* branch
        git branch -D "$BRANCH"
        ;;
    *)
        git checkout "$BRANCHFROM"
        git merge "$BRANCH" -m "Implement hotfix '$HOTFIXNAME'"
        git branch -d "$BRANCH"
        ;;
    esac

    if [ $? -eq 0 ]; then
        echo -e "\n⮕ ${green}Hotfix $HOTFIXNAME successfully implemented!${normal}\n"
    else
        echo -e "\n⮕ ${red}ERR: Problems occured during implementation of hotfix $HOTFIXNAME${normal}\n"
    fi
}

# pushes the branch to remote
function publishHotfix {
    git push -u origin "$BRANCH"
}

# abort if the [name] is missing and show the help
if [ -z "$2" ] && [ "$CMD" == "create" ]; then
    echo -e "\nERR: Parameter missing or command not found!\n"
    usage
    exit 1
fi

# abort if working directory is dirty
if [ "$WORKINGDIRDIRTY" ]; then
    echo -e "\n⮕ ${yellow}Warning:${normal} Your working directory is dirty!\n"
    git status
    echo -e "${yellow}"
    read -p "Proceed anyway? (Y/n) " proceedDirty
    echo -e "${normal}"

    if [ ! "$proceedDirty" == "Y" ]; then
        exit 1
    fi
fi

# the main logic handler.
case "$CMD" in
create)
    if [ "$BRANCHEXISTS" ]; then
        echo -e "\n${red}ERR: Branch $BRANCH already exists!${normal}\n"
        exit 1

    else
        git checkout -b "$BRANCH" "$BRANCHFROM"
    fi
    exit
    ;;

finish)
    finishHotfix
    exit
    ;;

publish)
    publishHotfix
    exit
    ;;

*)
    usage
    exit
    ;;

esac
