#!/bin/bash
#
# Usage: git feature start <name>
# Usage: git feature finish <name>
set -e

# Defaults
BRANCHPREFIX=$(git config --get oneflow.prefix.feature)
BRANCHFROM=$(git config --get oneflow.branch.next)
BRANCH="${BRANCHPREFIX}$2"

# Help function showing usage of the command
usage() {
    echo -e "Usage:\n\tgit feature start <name>"
    echo -e "\tgit feature finish <name>"
}

# merges feature branch into develop.
function createFeature {
    git checkout "$BRANCH"
    git rebase -i "$BRANCHFROM"
    git checkout "$BRANCHFROM"
    git merge --no-ff "$BRANCH"
    git push origin "$BRANCHFROM"
    git branch -d "$BRANCH"
}


function featureBranch {

    if [ -z "$2" ] ; then
        usage
        exit 0
    fi

    case "$1" in
        start)
            if git rev-parse --quiet --verify "$BRANCH" ; then
                echo "Branch $BRANCH already exists!"
                exit 0

            else
                if ! git status --porcelain ; then
                    git checkout -b "$BRANCH" "$BRANCHFROM"
                else
                    echo "Your working directory is dirty."
                    git status
                fi
            fi
            exit
            ;;

        finish)

            if ! git status --porcelain ; then
                createFeature
            else
                echo "Your working directory is dirty."
                git status
            fi
            exit
            ;;

        *)
            usage
            exit
            ;;

    esac
}

featureBranch "$1" "$2"